### ISSUE TITLE
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at

### ISSUE THREAD

**Issue by Hliu0313** [IIPCVLAB/LCCNet#21]

**Comment by Hliu0313** [comment]
已解决[https://github.com/pytorch/pytorch/issues/5046](url)

**Comment by Hliu0313** [comment]
错误答案，不能解决问题

**Comment by HXB-1997** [comment]
> 错误答案，不能解决问题

请问解决了吗？@Hliu0313

**Comment by Hliu0313** [comment]
> 



> > 错误答案，不能解决问题
> 
> 请问解决了吗？@Hliu0313

我现在方案使用CMRNet网络环境跑LCCNet，能够成功运行。

**Comment by HXB-1997** [comment]
> > 
> 
> > > 错误答案，不能解决问题
> > 
> > 
> > 请问解决了吗？@Hliu0313
> 
> 我现在方案使用CMRNet网络环境跑LCCNet，能够成功运行。

感谢，我去试试

**Comment by Hliu0313** [comment]
> > 错误答案，不能解决问题
> 
> 请问解决了吗？@Hliu0313

CMRNet对高版本pytorch兼容，先下载CMRNet代码，编译环境，复制他的corr包，到LCCNet中，可以使用。

**Comment by HXB-1997** [comment]
> > > 错误答案，不能解决问题
> > 
> > 
> > 请问解决了吗？@Hliu0313
> 
> CMRNet对高版本pytorch兼容，先下载CMRNet代码，编译环境，复制他的corr包，到LCCNet中，可以使用。
我的方案是LCCNet代码evaluate_calib.py的os.environ['CUDA_VISIBLE_DEVICES'] = '0'，就可以解决问题。代码作者本应该说明的。
